# Generated by Django 4.2.16 on 2024-12-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='vidoes/')),
                ('description', models.TextField(max_length=255, null=True)),
                ('videolinks', models.TextField(max_length=255, null=True)),
            ],
        ),
    ]
