# Generated by Django 4.2.16 on 2024-12-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePost', '0002_alter_moviepost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepost',
            name='video',
        ),
    ]
