# Generated by Django 4.2.16 on 2024-12-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePost', '0003_remove_moviepost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepost',
            old_name='videolinks',
            new_name='videolink',
        ),
    ]
